dist: xenial
language: python
python:
- '3.6'
stages:
- name: test
- name: deploy
jobs:
  include:
  - stage: test
    script:
    - ./base.sh
    - echo "testing"
    if: env(TRAVIS_PULL_REQUEST) != false
  - stage: deploy
    env:
    - ENV=dev
    script:
    - ./base.sh
    - echo "deploying to ${ENV}"
    if: branch = master
  - stage: deploy
    env:
    - ENV=qa
    script:
    - ./base.sh
    - echo "deploying to ${ENV}"
    if: branch = master
