dist: xenial
language: python
python:
- '3.6'
env:
  global:
  - MY_GLOBAL='my-global'
stages:
- name: test
jobs:
  include:
  - stage: test
    script:
    - echo "TRAVIS_BRANCH: ${TRAVIS_BRANCH}"
    - echo "TRAVIS_PULL_REQUEST_BRANCH: ${TRAVIS_PULL_REQUEST_BRANCH}"
    - echo "TRAVIS_PULL_REQUEST: ${TRAVIS_PULL_REQUEST}"
    - echo do-nothing
