dist: xenial
language: python
python:
- '3.6'
branches:
  only:
  - master
stages:
- name: test
- name: deploy
jobs:
  include:
  - stage: test
    script:
    - ./base.sh
    - echo "testing"
  - stage: deploy
    env:
    - ENV=dev
    script:
    - ./base.sh
    - echo "deploying to ${ENV}"
  - stage: deploy
    env:
    - ENV=qa
    script:
    - ./base.sh
    - echo "deploying to ${ENV}"
